### ISSUE TITLE
Prototype functions

### ISSUE THREAD

**Issue by nickdima** [hunterloftis/cryo#5]
Does it work with functions defined on an object's prototype? At a first look it doesn't seem so.

**Comment by wbyoung** [comment]
@nickdima @hunterloftis I don't think it should do anything with prototype functions. Instead I think you should be restoring the object to it's original type during `parse`. This can be achieved via the docs in #7.

**Comment by hunterloftis** [comment]
Handled by https://github.com/hunterloftis/cryo/pull/7
