### ISSUE TITLE
Objects of a given class

### ISSUE THREAD

**Issue by wbyoung** [hunterloftis/cryo#6]
As it stands, `cryo` can re-create objects, but recreates vanilla objects, not those of their original type.

Would you be open to a pull request that added functionality so that something like this would be possible:

```js
function Shape() {
  this.x = 0;
  this.y = 0;
}

var shape = new Shape();
var cryoShape = Cryo.parse(Cryo.stringify(shape));

shape instanceof Shape; // true
cryoShape instanceof Shape; // true
```

It would likely use [`__proto__`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto) and/or [`setPrototypeOf`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf) and may require a way for types to be found during `Cryo.parse`.

**Comment by hunterloftis** [comment]
Yep, would be open to a PR for that. It'd be a good idea to make sure it works in recent browsers / node.

**Comment by hunterloftis** [comment]
Handled by https://github.com/hunterloftis/cryo/pull/7
